import "./globals.css";

import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Rick and Morty API",
  description: "Generated by fek",
};

import { Raleway } from "next/font/google";

const font = Raleway({
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={font.className}>{children}</body>
    </html>
  );
}
